### ISSUE TITLE
cannot import name '_aligners' from partially initialized module 'Bio.Align'

### ISSUE THREAD

**Issue by rattei** [bergmanlab/mcclintock#115]
A fresh install of the conda environment gives us this error and breaks:
`Traceback (most recent call last):
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/share/mcclintock/testout/snakemake/4744464/.snakemake/scripts/tmp4gl3xdxz.make_reference_fasta.py", line 8, in <module>
    from Bio import SeqIO
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line 382, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.8/site-packages/Bio/Align/__init__.py", line 21, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners' from partially initialized module 'Bio.Align' (most likely due to a circular import) (/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.8/site-packages/Bio/Align/__init__.py)`

Python is version 3.8.2, packaged by conda-forge. Within python3, "from Bio.Align import _aligners" works well.

**Comment by cbergman** [comment]
HI @rattei 

Thanks for your report. To help us find a solution to your issue, can you please confirm that you followed the conda/mamba and mcclintock installation instructions step-by-step exactly as documented in the readme: https://github.com/bergmanlab/mcclintock#conda? 

The reason I ask is that installation of McClintock following the readme instructions should create the main mcclintock environment in `/home/apps/conda/miniconda3/envs/mcclintock/` not into `/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/`. 

If you have not followed the installation instructions exactly (or are not sure if you did), please remove your current mcclintock environment:

```
conda env remove -p /home/apps/conda/miniconda3/envs/mcclintock-2.0.0
```
Then make sure your mcclintock git repository is up to date:
```
cd mcclintock
git pull
```
Then do a full install (mcclintock environment creation and tool installation) following the installation instructions step-by-step exactly as in the readme: https://github.com/bergmanlab/mcclintock#install.

Thanks,
Casey

**Comment by rattei** [comment]
Yes, I confirm that the problem also occurs when we name the environment "mcclintock". BTW: to facilitate reproducible research, we strictly version our environments by including the versions in the environment names. It would be very sad if you would hardcode the name of the environment in your code, which wouldnt leave the user the freedom to chose environment names according to the user's needs.

Here is how we install mcclintock and reproduce the error, as fas as I could see this strictly follows your instructions:
URL='https://github.com/bergmanlab/mcclintock'
TD=$(mktemp -d)
pushd $TD
git clone --quiet $URL
cd mcclintock
conda env create --name mcclintock -f install/envs/mcclintock.yml
CONDA_BASE=$(conda info --base)
source ${CONDA_BASE}/etc/profile.d/conda.sh
conda activate mcclintock
python3 mcclintock.py --install
python3 test/download_test_data.py
python3 mcclintock.py -r test/sacCer2.fasta -c test/sac_cer_TE_seqs.fasta -g test/reference_TE_locations.gff -t test/sac_cer_te_families.tsv -1 test/SRR800842_1.fastq.gz -2 test/SRR800842_2.fastq.gz -p 4 -o testout 1>~/test.out 2>~/test.err
popd
rm -rf $TD

**Comment by cbergman** [comment]
Thanks for this additional information, we'll try to reproduce your error on our system. Can you please tell us what OS and version of OS you are using?

**Comment by rattei** [comment]
Sure. We run Oracle Linux 8.7 (equivalent with RHEL 8.7) with all packages up-to-date. Kernel: 4.18.0-425.19.2.el8_7.x86_64

**Comment by cbergman** [comment]
I am working through your issue, and one thing I see so far that differs from our installation instructions is that you are using conda to build your mcclintock environment, not mamba. Can you please try re-doing your installation using mamba (i.e. `mamba env create --name mcclintock -f install/envs/mcclintock.yml`) and see if that gives the same error? Thanks!

**Comment by rattei** [comment]
We have configured libmamba as solver for conda, which in theory should be the same. However, if I use mamba to create the environment, mcclintock seems to run without error. I will now analyse this in details, there is probably a difference in the installed packages. This is strange, as mcclintock was running in our setting for months without problems.

**Comment by cbergman** [comment]
Thanks for testing this so quickly. This is very strange indeed and I agree points to differences in different sets of dependencies installed by conda with mamba as the solver vs mamba itself. I’ll continue to investigate this, but please post what you find about dependency differences. I’ll keep this issue open until we get to the bottom of the problem. Thanks, Casey.
