### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Thatguy027** [bergmanlab/mcclintock#62]
Hi there,

I just started using mcclintock and have run into some issues.

Here it is:

Command:
```
    python3 ~/bin/mcclintock/mcclintock.py \\
		-r ${params.genome} \\
		-c ${params.con_seqs} \\
		-g ${params.ref_locs} \\
		-t ${params.families} \\
		-1 ${fq1} \\
		-2 ${fq2} \\
		-p ${task.cpus} \\
		-m ngs_te_mapper,temp,retroseq,te-locate \\
		-o mcclintock_out
```
Error:
```
Traceback (most recent call last):
  File "/projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/snakemake/1096582/.snakemake/scripts/tmpx20ygtgw.temp_post.py", line 154, in <module>
    main()
  File "/projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/snakemake/1096582/.snakemake/scripts/tmpx20ygtgw.temp_post.py", line 29, in main
    mccutils.make_nonredundant_bed(insertions, sample_name, out_dir, method="temp")
  File "/home/szs315/bin/mcclintock/scripts/mccutils.py", line 394, in make_nonredundant_bed
    if uniq_inserts[key].temp.support != "!" and insert.temp.support > uniq_inserts[key].temp.support:
TypeError: '>' not supported between instances of 'str' and 'float'
[Thu Jul 30 12:16:40 2020]
Error in rule process_temp:
    jobid: 0
    output: /projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/results/TEMP/BGI2-RET6-JU1440-trim-1P_temp_redundant.bed, /projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/results/TEMP/BGI2-RET6-JU1440-trim-1P_temp_nonredundant.bed
    conda-env: /home/szs315/bin/mcclintock/install/envs/conda/716bd1a3

RuleException:
CalledProcessError in line 498 of /projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/snakemake/1096582/Snakefile:
Command 'source /home/szs315/.pyenv/versions/miniconda3-4.3.27/bin/activate '/home/szs315/bin/mcclintock/install/envs/conda/716bd1a3'; set -euo pipefail;  /home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/mcclintock/bin/python3.8 /projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/snakemake/1096582/.snakemake/scripts/tmpx20ygtgw.temp_post.py' returned non-zero exit status 1.
  File "/projects/b1042/AndersenLab/work/stefan/ca/ff5ae5af5922d73544acee2c85de68/mcclintock_out/snakemake/1096582/Snakefile", line 498, in __rule_process_temp
  File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/mcclintock/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Exiting because a job execution failed. Look above for error message

```

I understand this is not the most useful error post, but I am running about a 1000 samples and decided to show you the error in case it makes sense to you. In the mean time, I am just skipping the sample that caused the issue.

Best

**Comment by pbasting** [comment]
@Thatguy027 Thanks for opening this issue. 

I've seen this error before and currently have fixed it on the [TEPID branch](https://github.com/bergmanlab/mcclintock/tree/TEPID). I'll merge these changes with master soon once I've tested that it is working as intended.

**Comment by Thatguy027** [comment]
oh great - there are some other weird errors i was getting with popoolation2 as well, but did not save them. if i can dig them up, i'll post another random error post. 

thanks for the quick response!

on a side note - is there a way to pre-configure the TE caller parameters?

**Comment by pbasting** [comment]
* Each component method has associated config files that can be modified to change parameters under `path/to/mcclintock/config/${method}/`. For example, the popoolationTE2 run config file is: https://github.com/bergmanlab/mcclintock/blob/master/config/popoolationte2/popoolationte2_run.py
* I have been testing everything using the default parameters so if you run into any issues when modifying the config files, please feel free to open an issue about it

**Comment by Thatguy027** [comment]
excellent, thank you very much!
